# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  repository_dispatch:
    types: [ "tldr-email-received" ]
  

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Create EML file from payload
      env:
        HTML_PAYLOAD: ${{ github.event.client_payload.html_content }}
      run: |
        echo "$HTML_PAYLOAD" > temp_newsletter.html
      

    - name: Run python TLDR parser script
      run: python tldr_extractor_v2.py temp_newsletter.html

    - name: Commit and push if it's changed.
      uses: stefanzweifel/git-auto-commit-action@v6
      with: 
        commit_message: "feat: Add new TLDR newsletter summary"
        add: "tldr_summaries/*.md"
        commit_user_name: TLDR Parser Script
